version: '3.8'

services:
  kong-database:
    image: postgres:latest
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-db:/var/lib/postgresql/data
    networks:
      - kong-network

  kong:
    image: kong:latest
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PORTAL: "on"
      KONG_PORTAL_GUI_HOST: 0.0.0.0
      KONG_PORTAL_GUI_PORT: 8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8002:8002"
    networks:
      - kong-network
    user: "1000:1000"

  kong-migrations:
    image: kong:latest
    depends_on:
      - kong-database
      - kong
    entrypoint: ["kong", "migrations", "bootstrap"]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    networks:
      - kong-network
    restart: "no"

volumes:
  kong-db:

networks:
  kong-network: